// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfVp-KgSVnEyvYBd6t4UmoMJjbS2_2sI',
    appId: '1:458008681909:web:0c714c67be76cde052cdfc',
    messagingSenderId: '458008681909',
    projectId: 'garment-a152b',
    authDomain: 'garment-a152b.firebaseapp.com',
    storageBucket: 'garment-a152b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPJKrLw3SKzX5IVzBhGpTgkOfo3HiVTk',
    appId: '1:458008681909:android:559c29c4cbcd025452cdfc',
    messagingSenderId: '458008681909',
    projectId: 'garment-a152b',
    storageBucket: 'garment-a152b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5zQTY6wnS_buq8OdWp1FkAb2T0ybYS0',
    appId: '1:458008681909:ios:cdbf0e920d061a8252cdfc',
    messagingSenderId: '458008681909',
    projectId: 'garment-a152b',
    storageBucket: 'garment-a152b.appspot.com',
    iosBundleId: 'com.example.garment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5zQTY6wnS_buq8OdWp1FkAb2T0ybYS0',
    appId: '1:458008681909:ios:cdbf0e920d061a8252cdfc',
    messagingSenderId: '458008681909',
    projectId: 'garment-a152b',
    storageBucket: 'garment-a152b.appspot.com',
    iosBundleId: 'com.example.garment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApfVp-KgSVnEyvYBd6t4UmoMJjbS2_2sI',
    appId: '1:458008681909:web:d230831059a5cc1052cdfc',
    messagingSenderId: '458008681909',
    projectId: 'garment-a152b',
    authDomain: 'garment-a152b.firebaseapp.com',
    storageBucket: 'garment-a152b.appspot.com',
  );
}
